// <auto-generated />
using System;
using Mainguard.Git;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Mainguard.Git.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Mainguard.Git.Models.ExpectedAgent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AgentId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DisposalReason")
                        .HasColumnType("TEXT");

                    b.Property<string>("Disposition")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RepoHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RepoHash", "AgentId")
                        .IsUnique();

                    b.ToTable("ExpectedAgents");
                });

            modelBuilder.Entity("Mainguard.Git.Models.GatewayBudget", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("TokenCap")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TokenCapPerDay")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UsdMicrosCap")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UsdMicrosCapPerDay")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("GatewayBudgets");
                });

            modelBuilder.Entity("Mainguard.Git.Models.GitProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("GpgFormat")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GpgProgram")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("SignCommits")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SigningKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("GitProfiles");
                });

            modelBuilder.Entity("Mainguard.Git.Models.JournalEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsTruncated")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsUndoable")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsUndone")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PostStateJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PreStateJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RepoPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UndoBlockedReason")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("WhenUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RepoPath");

                    b.ToTable("JournalEntries");
                });

            modelBuilder.Entity("Mainguard.Git.Models.MergeLeaseRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AgentId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("BeginUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Confirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExpectedMainSha")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LeaseId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MainBranch")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PostMergeSha")
                        .HasColumnType("TEXT");

                    b.Property<string>("RepoHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RepoHash");

                    b.ToTable("MergeLeaseRows");
                });

            modelBuilder.Entity("Mainguard.Git.Models.MergeQueueRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AgentId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DiscardReason")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DiscardedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DiscardedBy")
                        .HasColumnType("TEXT");

                    b.Property<long?>("LastVerificationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RepoHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("VerifiedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RepoHash", "AgentId")
                        .IsUnique();

                    b.ToTable("MergeQueueRows");
                });

            modelBuilder.Entity("Mainguard.Git.Models.PinnedRef", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RefName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RepoPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RepoPath", "RefName")
                        .IsUnique();

                    b.ToTable("PinnedRefs");
                });

            modelBuilder.Entity("Mainguard.Git.Models.PrIntakeConfigRow", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BotAuthors")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PollIntervalSeconds")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("PrIntakeConfig");
                });

            modelBuilder.Entity("Mainguard.Git.Models.PrIntakeHeadRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("PrNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SeenHeadSha")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SourceKey", "PrNumber")
                        .IsUnique();

                    b.ToTable("PrIntakeHeads");
                });

            modelBuilder.Entity("Mainguard.Git.Models.PrIntakeSubscriptionRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AuthorFilter")
                        .HasColumnType("TEXT");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Repo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Host", "Owner", "Repo", "AuthorFilter")
                        .IsUnique();

                    b.ToTable("PrIntakeSubscriptions");
                });

            modelBuilder.Entity("Mainguard.Git.Models.Repository", b =>
                {
                    b.Property<int>("RepositoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CustomIconColor")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastAccessed")
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("RepositoryId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Path")
                        .IsUnique();

                    b.ToTable("Repositories");
                });

            modelBuilder.Entity("Mainguard.Git.Models.SpendRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AgentId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Tokens")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UsdMicros")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("WhenUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.ToTable("SpendRecords");
                });

            modelBuilder.Entity("Mainguard.Git.Models.TosAcknowledgment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("AcknowledgedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Provider");

                    b.ToTable("TosAcknowledgments");
                });

            modelBuilder.Entity("Mainguard.Git.Models.VerificationRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AgentId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ConfigHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LogArtifactPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MainSha")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Passed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RepoHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ResolvedCommand")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("WhenUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RepoHash", "AgentId");

                    b.ToTable("VerificationRows");
                });

            modelBuilder.Entity("Mainguard.Git.Models.WorkspaceCategory", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParentCategoryId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CategoryId");

                    b.HasIndex("ParentCategoryId");

                    b.ToTable("WorkspaceCategories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            DisplayOrder = 1,
                            Name = "Personal"
                        },
                        new
                        {
                            CategoryId = 2,
                            DisplayOrder = 2,
                            Name = "Work"
                        });
                });

            modelBuilder.Entity("Mainguard.Git.Models.Repository", b =>
                {
                    b.HasOne("Mainguard.Git.Models.WorkspaceCategory", "Category")
                        .WithMany("Repositories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Mainguard.Git.Models.WorkspaceCategory", b =>
                {
                    b.HasOne("Mainguard.Git.Models.WorkspaceCategory", "ParentCategory")
                        .WithMany("SubCategories")
                        .HasForeignKey("ParentCategoryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("Mainguard.Git.Models.WorkspaceCategory", b =>
                {
                    b.Navigation("Repositories");

                    b.Navigation("SubCategories");
                });
#pragma warning restore 612, 618
        }
    }
}
